["1.21.11"]
minecraft_version = "1.21.11"
fabric_version = "0.141.6+1.21.11"
yacl_version = "3.8.2+1.21.11-fabric"
modmenu_version = "17.0.0"
java_version = 21

["26.1"]
minecraft_version = "26.1"
fabric_version = "0.145.1+26.1"
yacl_version = "3.9.6+26.1-fabric"
modmenu_version = "18.0.0"
java_version = 25

["26.1.1"]
minecraft_version = "26.1.1"
fabric_version = "0.145.4+26.1.1"
yacl_version = "3.9.6+26.1-fabric"
modmenu_version = "18.0.0"
java_version = 25

["26.1.2"]
minecraft_version = "26.1.2"
fabric_version = "0.155.2+26.1.2"
yacl_version = "3.9.6+26.1-fabric"
modmenu_version = "18.0.0"
java_version = 25

["26.2"]
minecraft_version = "26.2"
fabric_version = "0.156.0+26.2"
yacl_version = "3.9.6+26.2-fabric"
modmenu_version = "20.0.1"
java_version = 25
